version: '3.8'

services:
  web:
    image: tomcat:9-jdk21
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
  db:
    image: postgres:13.3-alpine
    volumes:
      - data_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
volumes:
  data_volume: